# Generated by Django 5.1.5 on 2025-02-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('old_testament', models.CharField(max_length=100)),
                ('new_testament', models.CharField(max_length=100)),
                ('psalm', models.CharField(max_length=100)),
            ],
        ),
    ]
