# Generated by Django 5.1.5 on 2025-03-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book', models.CharField(max_length=255, null=True)),
                ('chapter', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Old Testament', 'Old Testament'), ('New Testament', 'New Testament'), ('Psalm', 'Psalm')], max_length=50, null=True)),
            ],
        ),
    ]
