# Generated by Django 5.1.5 on 2025-03-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingPlan',
            new_name='BibleReading',
        ),
    ]
