# Generated by Django 5.1.5 on 2025-03-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_plan', '0002_rename_readingplan_biblereading'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biblereading',
            table='bible_readings',
        ),
    ]
